# Generated by Django 3.2.4 on 2021-06-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=4)),
                ('length', models.CharField(default='', max_length=100)),
                ('width', models.CharField(default='', max_length=100)),
                ('hin', models.CharField(default='', max_length=17)),
                ('color', models.CharField(default='', max_length=100)),
                ('curMileage', models.IntegerField(default=0)),
                ('service_interval', models.CharField(max_length=100)),
                ('next_service', models.DateTimeField(verbose_name='next service date')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=4)),
                ('seats', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('vin', models.CharField(default='', max_length=17)),
                ('curMileage', models.CharField(default='', max_length=100)),
                ('service_interval', models.CharField(max_length=100)),
                ('next_service', models.DateTimeField(verbose_name='next service date')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=4)),
                ('seats', models.CharField(default='', max_length=4)),
                ('bed_length', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=100)),
                ('vin', models.CharField(default='', max_length=17)),
                ('curMileage', models.IntegerField(default=0)),
                ('service_interval', models.CharField(max_length=100)),
                ('next_service', models.DateTimeField(verbose_name='next service date')),
            ],
        ),
    ]
