# Generated by Django 3.2.4 on 2021-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGarage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='next_service',
            field=models.DateField(verbose_name='next service date'),
        ),
        migrations.AlterField(
            model_name='car',
            name='next_service',
            field=models.DateField(verbose_name='next service date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='next_service',
            field=models.DateField(verbose_name='next service date'),
        ),
    ]
