# Generated by Django 3.2.4 on 2021-06-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGarage', '0002_auto_20210622_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='next_service',
            field=models.DateTimeField(verbose_name='next service date'),
        ),
    ]
