# Generated by Django 3.2.4 on 2021-06-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGarage', '0003_alter_car_next_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='next_service',
            field=models.DateField(verbose_name='next service date'),
        ),
    ]
