# Generated by Django 3.2.4 on 2021-06-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myGarage', '0005_auto_20210623_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='cur_mileage',
            new_name='cur_hours',
        ),
    ]
